"""fix typo

Revision ID: ddba48778eae
Revises: 38c9c4a52c6b
Create Date: 2025-12-02 22:13:03.955775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddba48778eae'
down_revision = '38c9c4a52c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('uq_users_username', ['username'])
        batch_op.drop_column('usrname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usrname', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint('uq_users_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
